[build]
  base = "/"
  publish = "dist/"
  command = "npm install && bundle e inesita build -f"

[[redirects]]
  from = "/api/*"
  to = "https://pc.fedorsmolov.keenetic.link/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
